[project]
requires-python = ">=3.12"
name = "StarTrek"

[tool.poetry]
name = "startrek"
version = "0.1.4"
description = "Star Trek Fleet Command Projects"
authors = ["Al Ferguson <aferguson@neptunescove.org>"]
license = "GNU3"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.31"

[tool.poetry.dev-dependencies]
mypy = "^1.51"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
