/*
# REST API examples for assets.stfc.space
*/
/*
## Global Variables
*/
@host = assets.stfc.space
@apiPath = data/latest
@translate = translations/en
@jsonType = application/json
@jsonEncoding = gzip, deflate
@jsonLanguage = en-US, en;q=0.9
@baseurl {{host}}/{{apiPath}}
/*
## Current stfc.space Database Version
*/
###
GET https://{{baseurl}}/version.txt
Accept: {{jsonType}}
Accept-Encoding: {{jsonEncoding}}
Accept-Language: {{jsonLanguage}}

HTTP/1.1 200  - OK
content-type: text/plain
content-length: 36
connection: close
date: Fri, 13 Oct 2023 21:19:10 GMT
last-modified: Fri, 13 Oct 2023 15:20:12 GMT
etag: "2d19d092030273d3ed20ee4beacea509"
x-amz-server-side-encryption: AES256
x-amz-version-id: m9uhNtK.w_jhp38CTEaWvufLHXvivipz
accept-ranges: bytes
server: AmazonS3
x-cache: Hit from cloudfront
via: 1.1 cc47ec2760d38b865200c4e75e0eec54.cloudfront.net (CloudFront)
x-amz-cf-pop: CMH68-P4
x-amz-cf-id: eX6_DtZQMbMDzfOqITFv6096nyQPnwKm1yQ4UY2n57Oy3Q9rGiuSAA==
age: 5815
vary: Origin
/*
## Blueprint Information
*/
###
GET https://{{baseurl}}/{{translate}}/blueprints.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}

HTTP/1.1 200  - OK
content-type: application/json
transfer-encoding: chunked
connection: close
date: Fri, 13 Oct 2023 21:31:52 GMT
last-modified: Fri, 13 Oct 2023 15:11:34 GMT
etag: W/"d9c51c510b0a08d66486df4ef7f43ef1"
x-amz-server-side-encryption: AES256
x-amz-version-id: mHkYJyCvONOPuaD4WZD9_HopGWd.SL.C
server: AmazonS3
content-encoding: gzip
vary: Accept-Encoding, Origin
x-cache: Hit from cloudfront
via: 1.1 9bb4d05ab08e4eaa205fa572ca4c835c.cloudfront.net (CloudFront)
x-amz-cf-pop: CMH68-P4
x-amz-cf-id: QUFTT_3bPvAGlMPuNJTc5YENNPDA17VWGKBxQKRWJbfu2gkW4NA7kg==
age: 4234
/*
## Building Information
*/
###
GET https://{{baseurl}}/building/summary.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}

HTTP/1.1 200  - OK
content-type: application/json
transfer-encoding: chunked
connection: close
date: Fri, 13 Oct 2023 22:24:15 GMT
last-modified: Fri, 13 Oct 2023 15:06:52 GMT
etag: W/"4ee75cf484d686794fa9d036985d3938"
x-amz-server-side-encryption: AES256
x-amz-version-id: JKmgceVqZJVNAVpRL6tIREE9vKmLvvNK
server: AmazonS3
content-encoding: gzip
vary: Accept-Encoding, Origin
x-cache: Hit from cloudfront
via: 1.1 02a2bd1a95c9e133cb6af71565738388.cloudfront.net (CloudFront)
x-amz-cf-pop: CMH68-P4
x-amz-cf-id: E8WX_qSvQJ_il3FxEWiTcgyyqgd1o0f4phhQhea7jOTrtu4Rg4m8DA==
age: 1118
/*
## Consumable Information
- Consumable Details
- Consumable Titles and Descriptions
*/
###
GET https://{{baseurl}}/consumable/summary.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
###
GET https://{{baseurl}}/{{translate}}/consumables.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}

HTTP/1.1 200  - OK
content-type: application/json
transfer-encoding: chunked
connection: close
date: Fri, 13 Oct 2023 22:55:00 GMT
last-modified: Fri, 13 Oct 2023 15:11:34 GMT
etag: W/"38d4f54d84e908f6dd1ff083b5b9d07a"
x-amz-server-side-encryption: AES256
x-amz-version-id: YxQr.9bmXu1PIsykNaJkUfVvJAn6tsrS
server: AmazonS3
content-encoding: gzip
vary: Accept-Encoding, Origin
x-cache: Miss from cloudfront
via: 1.1 141cc765667839ffa8c4ad646af354cc.cloudfront.net (CloudFront)
x-amz-cf-pop: CMH68-P4
x-amz-cf-id: RVUbl4a7_IXi3BRuU2WAFWZ-pBVZrGCYzORM-vxPTI5aTank8HCrlg==
/*
## Event Titles
*/
###
GET https://{{baseurl}}/{{translate}}/event_titles.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
/*
## Faction information
*/
###
GET https://{{baseurl}}/{{translate}}/factions.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
/*
## Forbidden Tech Information
*/
###
GET https://{{baseurl}}/forbidden_tech/summary.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
/*
## Hostile Information
*/
###
GET https://{{baseurl}}/hostile/summary.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
/*
## Miscellaneous Material Information
- Assignment Speedups
- Repair Speedups

*/
###
GET https://{{baseurl}}/{{translate}}/materials.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}

HTTP/1.1 200  - OK
content-type: application/json
transfer-encoding: chunked
connection: close
date: Fri, 13 Oct 2023 21:42:52 GMT
last-modified: Fri, 13 Oct 2023 15:11:35 GMT
etag: W/"c1bf2907bf4d6c892ede1c60a7f90abf"
x-amz-server-side-encryption: AES256
x-amz-version-id: c_1VA5Dego8ksQ7IalEUwkjuo04XAUz1
server: AmazonS3
content-encoding: gzip
vary: Accept-Encoding, Origin
x-cache: Hit from cloudfront
via: 1.1 cc47ec2760d38b865200c4e75e0eec54.cloudfront.net (CloudFront)
x-amz-cf-pop: CMH68-P4
x-amz-cf-id: Xq5dc8rU8R1Q5M8iSnHYTBZH1pAGh2nwBhukf9yQ_AQw-aYAi3iH8Q==
age: 4080
###
GET https://{{baseurl}}/mission/summary.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
###
GET https://{{baseurl}}/{{translate}}/mission_titles.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
###
GET https://{{baseurl}}/{{translate}}/navigation.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
/*
## Officer Information
- Officer Detail Information
- Officer Additional Information
_ Officer Buffs
- Officer "flavor" Information
- Officer Names
- Officer Traits
*/
###
GET https://{{baseurl}}/officer/summary.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
###
GET https://{{baseurl}}/{{translate}}/officers.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
###
GET https://{{baseurl}}/{{translate}}/officer_buffs.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
###
GET https://{{baseurl}}/{{translate}}/officer_flavor_text.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
###
GET https://{{baseurl}}/{{translate}}/officer_names.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
###
GET https://{{baseurl}}/{{translate}}/traits.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
/*
## Player Avatar Information
*/
###
GET https://{{baseurl}}/{{translate}}/player_avatars.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
/*
## Research Information
- Research Details
- Research Titles and Descriptions
*/
###
GET https://{{baseurl}}/research/summary.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
###
GET https://{{baseurl}}/{{translate}}/research.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
/*
## Resource Information
*/
###
GET https://{{baseurl}}/resource/summary.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
/*
## Ship Information
- Ship Details
- Ship Names, Flavors, and Descriptions
- Ship Buffs
- Ship Components
- Ship Skins
*/
###
GET https://{{baseurl}}/ship/summary.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
###
GET https://{{baseurl}}/{{translate}}/ships.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
###
GET https://{{baseurl}}/{{translate}}/ship_buffs.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
###
GET https://{{baseurl}}/{{translate}}/ship_components.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
###
GET https://{{baseurl}}/skins/summary.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
/*
## Star Base Information
*/
###
GET https://{{baseurl}}/{{translate}}/starbase_modules.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
/*
## Syndicate Information
*/
###
GET https://{{baseurl}}/syndicate/summary.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
/*
## Faction Loyalty information
*/
###
GET https://{{baseurl}}/{{translate}}/loyalty.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}
/*
## System Information
- System Detail Information
- System Names, Flavor, and Description Information
*/
###
GET https://{{baseurl}}/system/summary.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}

HTTP/1.1 200  - OK
content-type: application/json
transfer-encoding: chunked
connection: close
date: Fri, 13 Oct 2023 20:05:27 GMT
last-modified: Fri, 13 Oct 2023 15:09:39 GMT
etag: W/"763b0dde10cffde4f156a10fbb838fe6"
x-amz-server-side-encryption: AES256
x-amz-version-id: dtsRmnGbjdmoXFfCIMjJdj2nGVrPtqVx
server: AmazonS3
content-encoding: gzip
vary: Accept-Encoding, Origin
x-cache: Hit from cloudfront
via: 1.1 3e15e20983f10122d7332649559a0f8c.cloudfront.net (CloudFront)
x-amz-cf-pop: ORD58-P6
x-amz-cf-id: H9eScIsN6iqFh0cXm-5-qqrBNEW7py4MtQ6fWUNjyOtVPpVRFFbTSA==
age: 8340
###
GET https://{{baseurl}}/{{translate}}/systems.json HTTP/1.1
    Accept: {{jsonType}}
    Accept-Encoding: {{jsonEncoding}}
    Accept-Language: {{jsonLanguage}}

HTTP/1.1 200  - OK
content-type: application/json
transfer-encoding: chunked
connection: close
date: Fri, 13 Oct 2023 20:04:08 GMT
last-modified: Fri, 13 Oct 2023 15:12:31 GMT
etag: W/"af2c3a6762dec81231b4f8effef2ae25"
x-amz-server-side-encryption: AES256
x-amz-version-id: MVrWzj.93Yyqu64Mli09l5m8_QWtIHPb
server: AmazonS3
content-encoding: gzip
vary: Accept-Encoding, Origin
x-cache: Hit from cloudfront
via: 1.1 e807928bf10df259d5d9aa45c69572c8.cloudfront.net (CloudFront)
x-amz-cf-pop: ORD58-P6
x-amz-cf-id: UeiabpZIO1ajdqe5hmMAZ7R86K28v_N052tVgC9tXTrFBSmWxZAY1g==
age: 8416