### https://api.stfc.dev/v1 Reset API examples

@host = api.stfc.dev
@apiPath = v1
@translate = translations/en
@jsonType = application/json

@baseurl = https://{{host}}/{{apiPath}}


###
### Get stfc.space Database Version
GET {{baseurl}}/version HTTP/1.1
    Accept: {{jsonType}}


##
### Get Ship Information
GET {{baseurl}}/ship HTTP/1.1
    Accept: {{jsonType}}

### Get Ship Name
GET {{baseurl}}/{{translate}}/ships HTTP/1.1
    Accept: {{jsonType}}

### Get Ship Type
GET {{baseurl}}/{{translate}}/ship_type HTTP/1.1
    Accept: {{jsonType}}

### Get Ship Components
GET {{baseurl}}/{{translate}}/ship_components HTTP/1.1
    Accept: {{jsonType}}


###
### Get Faction Information
GET {{baseurl}}/faction HTTP/1.1
    Accept: {{jsonType}}

### Get Faction Detail Information
GET {{baseurl}}/{{translate}}/factions HTTP/1.1
    Accept: {{jsonType}}


###
### Get Galaxy information
GET {{baseurl}}/galaxy HTTP/1.1
    Accept: {{jsonType}}


###
### Get System information
GET {{baseurl}}/system HTTP/1.1
    Accept: {{jsonType}}

### Get System Detail information
GET {{baseurl}}/{{translate}}/systems HTTP/1.1
    Accept: {{jsonType}}


###
### Get Officer information
GET {{baseurl}}/officer HTTP/1.1
    Accept: {{jsonType}}

### Get Officer Detail information
GET {{baseurl}}/{{translate}}/officers HTTP/1.1
    Accept: {{jsonType}}

### Get Officer Synergy information
GET {{baseurl}}/{{translate}}/officers_synergy HTTP/1.1
    Accept: {{jsonType}}

### Get Officer Devision information
GET {{baseurl}}/{{translate}}/officer_division HTTP/1.1
    Accept: {{jsonType}}

### Get Officer Trait Information
GET {{baseurl}}/{{translate}}/traits HTTP/1.1
    Accept: {{jsonType}}


###
### Get Building information
GET {{baseurl}}/building HTTP/1.1
    Accept: {{jsonType}}

### Get Building Detail information
GET {{baseurl}}/{{translate}}/buildings HTTP/1.1
    Accept: {{jsonType}}

### Get Building Buff information
GET {{baseurl}}/{{translate}}/building_buffs HTTP/1.1
    Accept: {{jsonType}}


###
### Get Research information
GET {{baseurl}}/research HTTP/1.1
    Accept: {{jsonType}}

### Get Research Detail information
GET {{baseurl}}/{{translate}}/research HTTP/1.1
    Accept: {{jsonType}}


###
### Get Consumable information
GET {{baseurl}}/consumable HTTP/1.1
    Accept: {{jsonType}}

### Get Consumable Detail information
GET {{baseurl}}/{{translate}}/consumables HTTP/1.1
    Accept: {{jsonType}}


###
### Get Hostile information
GET {{baseurl}}/hostile HTTP/1.1
    Accept: {{jsonType}}

### Get Hostile Detail information
GET {{baseurl}}/{{translate}}/hostiles HTTP/1.1
    Accept: {{jsonType}}


###
### Get Mission information
GET {{baseurl}}/mission HTTP/1.1
    Accept: {{jsonType}}

### Get Mission Detail information
GET {{baseurl}}/{{translate}}/missions HTTP/1.1
    Accept: {{jsonType}}

### Get Mission Unlock information
GET {{baseurl}}/galaxy/mission_unlocks HTTP/1.1
    Accept: {{jsonType}}


###
### Get Material Detail information
GET {{baseurl}}/{{translate}}/materials HTTP/1.1
    Accept: {{jsonType}}


###
### Get Syndicate information
GET {{baseurl}}/syndicate HTTP/1.1
    Accept: {{jsonType}}

### Get Syndicate Detail Information
GET {{baseurl}}/{{translate}}/syndicate HTTP/1.1
    Accept: {{jsonType}}
